/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view_controller;

import javax.swing.JOptionPane;
import model.Ranking;

/**
 *
 * @author giadatrevisani
 */
public class InsertYear extends javax.swing.JFrame {
    private ViewCalendar father;
    private final Ranking rank;
    
    public InsertYear(Ranking rank, String sport, ViewCalendar father) {
        this.father = father;
        this.rank = rank;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setTitle(sport);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yearlbl = new javax.swing.JLabel();
        yeartxt = new javax.swing.JTextField();
        yearbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        yearlbl.setText("Inserire anno:");

        yearbtn.setText("Inserisci");
        yearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(yearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(yearlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(yeartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(yeartxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(yearbtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo per settare l'anno del calendario.
     * Questa classe sarà utilizzata dentro la classe ViewCalendar nel bottone
     * crea calendario.
     * @param evt 
     */
    private void yearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearbtnActionPerformed
        if(yeartxt.getText().equals("")){
            System.out.println("Inserire l'anno");
            JOptionPane.showMessageDialog(null, "Inserire l'anno");
        } else {
            rank.getCalendar().setYear(Integer.parseInt(yeartxt.getText()));
            father.insertYearlbl.setText(yeartxt.getText());
        }
    }//GEN-LAST:event_yearbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton yearbtn;
    private javax.swing.JLabel yearlbl;
    private javax.swing.JTextField yeartxt;
    // End of variables declaration//GEN-END:variables
}
