/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view_controller;

import java.awt.Dimension;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.Ranking;
import model.Team;

/**
 *
 * @author giadatrevisani
 */
public class ManagementTeams extends javax.swing.JFrame {
    Ranking rank;
    private final DefaultTableModel model;
    
    private boolean openNewTeam, openViewUpdate;
    
    
    
    public ManagementTeams(Ranking rank){
        this.rank = rank;
        initComponents();
        model = (DefaultTableModel) viewTeams.getModel();
        openNewTeam = false;
        openViewUpdate = false;
        
        
        rank.addTeam("sv150", "soliera", "Soliera.jpg");
        rank.addTeam("everton", "reggio emilia", "Modena.jpg");
        rank.addTeam("libertas", "fiorano", "Libertas.png");
        rank.addTeam("beta", "magreta", "cguidshs");
        rank.addTeam("alpha", "beta", "cguidshs");
        rank.addTeam("hsi", "soliera", "ehwewo");
        rank.addTeam("dbqhkdkq", "dbwjk", "bdjqk");
        rank.addTeam("asopaè", "soliera", "ckpdsa");
        rank.addTeam("shaksol", "soliera", "sapqm");
        rank.addTeam("tati", "soliera", "slaovs");
        rank.addTeam("dnkla", "eiiwa", "sndls");
        rank.addTeam("sqoausu", "sjwiqoabt", "aqde i");
        rank.addTeam("ql1p3udn", "slwpqle", "xlxsps,sx");
        rank.addTeam("aòspd 3", "dmspa", "xmosapa");
        rank.addTeam("jspx ps", "anozap", "sakopad");
        rank.addTeam("skaè'xkols", "2ko2p3nde", "jqopsjqw");
        rank.addTeam("whqioqd", "dwiqoa", "dwjqopdq");
        rank.addTeam("wqpidxpo", "3ipoe3r3", "dsjqopq");
        rank.addTeam("xcjsi", "ewi0ew", "weopq");
        rank.addTeam("si'osap", "dsjio", "dnsksa");
        rank.addTeam("dkpsa", "sajpsa", "ewjopf");
        rank.addTeam("dièasa", "magcnsreta", "cguiddcshs");
        rank.addTeam("bestdad", "masadgdrfcedvta", "cgvdsvusidvsshs");
        rank.addTeam("besta", "magareta", "cguidsbgdhs");
        rank.addTeam("qddcxds", "magrcascaeta", "cguidshs");
        rank.addTeam("dqwdq", "magretdqdqa", "cguidshs");
        rank.addTeam("dsdsawq", "magradceta", "cguidshs");
        rank.addTeam("baedtwa", "madasgreddta", "adscwv");
        printTable();
        this.creaGui();
    }
    
    private void creaGui() {
       this.setMinimumSize(new Dimension(700, 500));
       this.setSize(800, 600); 
    }
    
    private void printTable(){
        model.setRowCount(0);
        for (int i = 0; i < rank.getTeam().size(); i++) {
            model.insertRow(i, new Object[]{rank.getTeam().get(i).getName(), rank.getTeam().get(i).getCity(), rank.getTeam().get(i).getLogo()} );
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchTeams = new javax.swing.JTextField();
        newbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewTeams = new javax.swing.JTable();
        takeTeamsbtn = new javax.swing.JButton();
        saveTeamsbtn = new javax.swing.JButton();
        searchbtn = new javax.swing.JButton();
        finebtn = new javax.swing.JButton();
        viewbtn = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(0, 0));

        searchTeams.setToolTipText("");
        searchTeams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTeamsActionPerformed(evt);
            }
        });
        searchTeams.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTeamsKeyReleased(evt);
            }
        });

        newbtn.setText("New");
        newbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbtnActionPerformed(evt);
            }
        });

        viewTeams.setAutoCreateRowSorter(true);
        viewTeams.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Città", "Logo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(viewTeams);

        takeTeamsbtn.setText("<html><p style = \"text-align: center\">Carica Squadre<br>Da File</p></html>");
        takeTeamsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeTeamsbtnActionPerformed(evt);
            }
        });

        saveTeamsbtn.setText("Salva Squadre");
        saveTeamsbtn.setName("jnjn"); // NOI18N
        saveTeamsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTeamsbtnActionPerformed(evt);
            }
        });

        searchbtn.setText("cerca");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        finebtn.setBackground(new java.awt.Color(255, 0, 0));
        finebtn.setText("x");
        finebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finebtnActionPerformed(evt);
            }
        });

        viewbtn.setText("<html><p style = \"text-align: center\">Visualizza<br>Modifica</p></html>");
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(takeTeamsbtn)
                                    .addComponent(saveTeamsbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(viewbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchTeams, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTeams, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbtn)
                    .addComponent(finebtn))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(viewbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveTeamsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(takeTeamsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Questo metodo crea un nuovo oggetto Team vuoto e lo passa alla classe NewTeam
     * dove sarà inserita la nuova squadra.
     * @param evt 
     */
    private void newbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbtnActionPerformed
        if(openNewTeam == false){ 
            openNewTeam = true;
            Team nt = new Team("", "", "");
            NewTeam newTeam;
            
            newTeam = new NewTeam(nt, rank);
            newTeam.setVisible(true);
            newTeam.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                    openNewTeam = false;
                }
            });
        }
    }//GEN-LAST:event_newbtnActionPerformed

    /**
     * Questo metodo prende i teams presenti nel file JSON teams.json e li salva
     * nell'array teams presenti nell'oggetto rank.
     * @param evt 
     */
    private void takeTeamsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeTeamsbtnActionPerformed
        rank.takeFromFile();
        printTable();
    }//GEN-LAST:event_takeTeamsbtnActionPerformed

    private void searchTeamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTeamsActionPerformed
    
    }//GEN-LAST:event_searchTeamsActionPerformed

    /**
     * Questo metodo salva i teams presenti nell'array teams dell'oggetto rank
     * nel file JSON teams.json
     * @param evt 
     */
    private void saveTeamsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTeamsbtnActionPerformed
        try {
            rank.saveTeams();
        } catch (FileNotFoundException ex) {
            System.out.println("SAlvataggio non avvenuto");
        }
        
    }//GEN-LAST:event_saveTeamsbtnActionPerformed

    private void searchTeamsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTeamsKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTeamsKeyReleased

    /**
     * Questo metodo cerca la squadra inserita nella TextField searchTeam e visualizza
     * il/i risultati nella tabella.
     * @param evt 
     */
    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        int j = 0;
        model.setRowCount(0);
        for (int i = 0; i < rank.getTeam().size(); i++) {
            if(rank.getTeam().get(i).getName().equals(searchTeams.getText()) || rank.getTeam().get(i).getCity().equals(searchTeams.getText())){
                
                model.insertRow(j, new Object[]{rank.getTeam().get(i).getName(), rank.getTeam().get(i).getCity(), rank.getTeam().get(i).getLogo()} );
                j++;
            }
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    /**
     * Questo metodo ripristina la tabella iniziale dopo che ho cercato una squadra.
    */
    private void finebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finebtnActionPerformed
        searchTeams.setText("");
        printTable();
    }//GEN-LAST:event_finebtnActionPerformed

    /**
     * Questo metodo chiama una nuova finestra dove verrà visualizzato il team che si è cliccato nella tabella.
     * Cliccando sul bottone Modifica Visualizza è possibile anche modificare la squadra che si è cliccata nella tabella.
     * @param evt 
     */
    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed
        if(openViewUpdate == false){ 
            openViewUpdate = true;
            int selectedRowIndex = viewTeams.getSelectedRow();
            Team view_update;
            view_update = new Team(viewTeams.getModel().getValueAt(selectedRowIndex, 0).toString(), viewTeams.getModel().getValueAt(selectedRowIndex, 1).toString(), viewTeams.getModel().getValueAt(selectedRowIndex, 2).toString());
            NewTeam newTeam;

            newTeam = new NewTeam(view_update, rank);
            newTeam.setVisible(true);
            newTeam.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                    openViewUpdate = false;
                }
            });
        }
    }//GEN-LAST:event_viewbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton finebtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newbtn;
    private javax.swing.JButton saveTeamsbtn;
    private javax.swing.JTextField searchTeams;
    private javax.swing.JButton searchbtn;
    private javax.swing.JButton takeTeamsbtn;
    private javax.swing.JTable viewTeams;
    private javax.swing.JButton viewbtn;
    // End of variables declaration//GEN-END:variables

}
