/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view_controller;

import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import model.Ranking;
import model.Team;

/**
 *
 * @author giadatrevisani
 */
public class NewTeam extends javax.swing.JFrame {
    private final Ranking rank;
    private final Team team;
    private final String filePath = "img_logo/";
    /**
     * Il cotruttore dlla calsse NewTeam prende in ingresso il team che si vuole
     * aggiungere o aggiornare e l'oggetto di tipo Ranking dove andremo a salvare
     * le squadre da aggiungere o da aggiornare attraverso il bottone btnNew.
     * Ci sarà anche un bottone per cercare il logo della squadra tra quelli
     * presenti nella directory img_logo.
     */
    public NewTeam(Team team, Ranking rank){
        this.rank = rank;
        this.team = team;
        initComponents();
        
        printTeam();
        this.creaGui();
    }
    
    private void creaGui(){
        this.setMinimumSize(new Dimension(700, 500));
        this.setSize(800, 600); 
        
    }
    
    private void printTeam(){
        txtName.setText(team.getName());
        txtCity.setText(team.getCity());
        try{
        lblimg.setIcon(new ImageIcon(ImageIO.read(new File(filePath + team.getLogo()))));
        } catch (IOException ex){
            System.out.println("immagine non esistente");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        lblimg = new javax.swing.JLabel();
        deletebtn = new javax.swing.JButton();
        btnFindLogo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblName.setText("Nome: ");

        lblCity.setText("Città: ");

        lblLogo.setText("Logo: ");

        btnNew.setText("Nuovo/Aggiorna");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        deletebtn.setText("Elimina");

        btnFindLogo.setText("...");
        btnFindLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindLogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                .addComponent(txtCity))
                            .addComponent(lblimg, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFindLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCity)
                    .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnFindLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblimg, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(deletebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Inizialmente controlleremo se nel team passato il nome della squadra è
    * una stringa vuota, allora vuol dire che l'utente ha cliccato su nuova squadra.
    * Quindi andrò a verificare che i campi di testo txtName e txtCity siano riempiti,
    * in caso contrario il programma stamperà un messaggio.
    * A questo punto, se non è una squadra nuova allora sarà una squadra che voglio
    * aggiornare, quindi per prima cosa guarderò se effettivamente i capi text sono
    * stati cambiati oppure no (in quest'ultimo caso stamperò un messaggio). Come 
    * seconda cosa aggiornerò la squadra.
     * @param evt 
     */
    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        if(team.getName() == ""){
            if(txtName.getText().equals("") || txtCity.getText().equals("")){
                System.out.println("Uno dei campi è vuoto");
            } else {
                rank.addTeam(txtName.getText(), txtCity.getText(), lblimg.getText());
                System.out.println("Inserisco");
            }
        } else {
            if(txtName.getText().equals(team.getName()) && txtCity.getText().equals(team.getCity()) && lblimg.getText().equals(team.getLogo())){
                System.out.println("La squadra non è stata modificata");
            } else {
                for (int i = 0; i < rank.getTeam().size(); i++) {
                    if(rank.getTeam().get(i).equals(team)){
                        rank.getTeam().get(i).setName(txtName.getText());
                        rank.getTeam().get(i).setCity(txtCity.getText());
                        rank.getTeam().get(i).setLogo(lblimg.getText());
                        System.out.println("Squadra aggiornata");
                    }
                }
                
            }
        }
        
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnFindLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindLogoActionPerformed
        AddLogo addLogo = new AddLogo(this);
        addLogo.setVisible(true);
        
    }//GEN-LAST:event_btnFindLogoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFindLogo;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton deletebtn;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblimg;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
