/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view_controller;

import java.io.FileNotFoundException;
import javax.swing.table.DefaultTableModel;
import model.Calendar;
import model.Match;
import model.Ranking;

/**
 *
 * @author giadatrevisani
 */
public class ViewCalendar extends javax.swing.JFrame {
    private Ranking rank;
    private Calendar calendario;
    private final DefaultTableModel model;
    private boolean openViewUpdate;
    
    public ViewCalendar(Calendar calendario, Ranking rank){
        openViewUpdate = false;
        this.rank = rank;
        this.calendario = calendario;
        initComponents();
        model = (DefaultTableModel) viewCalendar.getModel();
        
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        calendario.setYear(2018);
        calendario.AlgoritmoDiBerger(rank.getTeam());
        printTable();
    }
    
    private void printTable(){
        model.setRowCount(0);
        for(int i = 0; i < calendario.getGames().size(); i++){
            model.insertRow(i, new Object[]{calendario.getGames().get(i).getDay(), calendario.getGames().get(i).getHomeTeam().getCity(), calendario.getGames().get(i).getHomeTeam().getName(), calendario.getGames().get(i).getGuestTeam().getName(), calendario.getGames().get(i).getPointsHome(), calendario.getGames().get(i).getPointsGuest()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchtxt = new javax.swing.JTextField();
        finebtn = new javax.swing.JButton();
        serachbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewCalendar = new javax.swing.JTable();
        javax.swing.JButton takeCalendarbtn = new javax.swing.JButton();
        saveCalendarbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        viewbtn = new javax.swing.JButton();
        printbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        finebtn.setText("X");
        finebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finebtnActionPerformed(evt);
            }
        });

        serachbtn.setText("cerca");
        serachbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serachbtnActionPerformed(evt);
            }
        });

        viewCalendar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Giornata", "Città", "Squadra Casa", "Squadra Ospite", "Punti Casa", "Punti Ospite", "Giocata"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(viewCalendar);

        takeCalendarbtn.setText("<html><p style = \"text-align: center\">Carica <br>Campionato</p></html>");
        takeCalendarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeCalendarbtnActionPerformed(evt);
            }
        });

        saveCalendarbtn.setText("<html><p style = \"text-align: center\">Salva <br>Campionato</p></html>");
        saveCalendarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCalendarbtnActionPerformed(evt);
            }
        });

        deletebtn.setText("<html><p style = \"text-align: center\">Elimina<br>Risultati</p></html>");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        viewbtn.setText("<html><p style = \"text-align: center\">Modifica<br>Visualizza</p></html>");
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });

        printbtn.setText("Stampa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(serachbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(takeCalendarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(saveCalendarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(printbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(finebtn)
                        .addComponent(serachbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(viewbtn))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deletebtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(printbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(takeCalendarbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(saveCalendarbtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finebtnActionPerformed
        searchtxt.setText("");
        printTable();
    }//GEN-LAST:event_finebtnActionPerformed

    private void serachbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serachbtnActionPerformed
        int j = 0;
        model.setRowCount(0);
        for (int i = 0; i < calendario.getGames().size(); i++) {
            if(calendario.getGames().get(i).getHomeTeam().getName().equals(searchtxt.getText()) || calendario.getGames().get(i).getGuestTeam().getName().equals(searchtxt.getText()) || searchtxt.equals(calendario.getYear())){
                model.insertRow(j, new Object[]{calendario.getGames().get(i).getDay(), calendario.getGames().get(i).getHomeTeam().getCity(),calendario.getGames().get(i).getHomeTeam().getName(), calendario.getGames().get(i).getGuestTeam().getName(), calendario.getGames().get(i).getPointsHome(), calendario.getGames().get(i).getPointsGuest(), calendario.getGames().get(i).getPlayed()} );
                j++;
            }
        }
    }//GEN-LAST:event_serachbtnActionPerformed

    private void takeCalendarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeCalendarbtnActionPerformed
        calendario.takeFromFile(rank.getTeam());
        printTable();
    }//GEN-LAST:event_takeCalendarbtnActionPerformed

    private void saveCalendarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCalendarbtnActionPerformed
        try {
            calendario.saveCalendar();
            System.out.println("Salvato su file");
        } catch (FileNotFoundException ex) {
            System.out.println("SAlvataggio non avvenuto");
        }
    }//GEN-LAST:event_saveCalendarbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        calendario.deleteResults();
        printTable();
    }//GEN-LAST:event_deletebtnActionPerformed

    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed
        if(openViewUpdate == false){ 
            openViewUpdate = true;
            int selectedRowIndex = viewCalendar.getSelectedRow();
            Match view_update;
            //devo creare un match solo con le cose che ho nella tabella... problema!!!
            /*
            view_update = new Match(viewCalendar.getModel().getValueAt(selectedRowIndex, 0), viewCalendar.getModel().getValueAt(selectedRowIndex, 1).toString(), viewCalendar.getModel().getValueAt(selectedRowIndex, 2).toString(), viewCalendar.getModel().getValueAt(selectedRowIndex, 3).toString(), viewCalendar.getModel().getValueAt(selectedRowIndex, 4), viewCalendar.getModel().getValueAt(selectedRowIndex, 5), viewCalendar.getModel().getValueAt(selectedRowIndex, 6));
            ViewMatch viewMatch;

            viewMatch = new ViewMatch(view_update, calendario);
            viewMatch.setVisible(true);
            viewMatch.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                    openViewUpdate = false;
                }
            });
            */
        }
    }//GEN-LAST:event_viewbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton finebtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printbtn;
    private javax.swing.JButton saveCalendarbtn;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JButton serachbtn;
    private javax.swing.JTable viewCalendar;
    private javax.swing.JButton viewbtn;
    // End of variables declaration//GEN-END:variables
}
